version: '3.8'

services:
  nodejs-api:
    container_name: 'canary-api'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./logs:/root/.npm/_logs
    command: npm start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server-c.entrypoints=websecure"
      - "traefik.http.services.server-c.loadbalancer.server.port=3000"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
