# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: true
  insecure: true  # Set to false in production and use proper authentication

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-network
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

# Configure certificate resolver for Cloudflare
certificatesResolvers:
  my-resolver:
    acme:
      email: delwinmathew2004@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare

# Configure log levels
log:
  level: DEBUG

accessLog:
  filePath: "./logs/traefik-s1-access.log"
  format: "common"
  bufferingSize: 100
