http:
  middlewares:
    secureHeaders:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    compress:
      compress: {}

  routers:
    # Canary router - matches X-Version: canary header
    server-c-canary:
      rule: "Host(`s1.server.plansync.in`) && Headers(`X-Version`, `canary`)"
      entryPoints:
        - "web"
        - "websecure"
      middlewares:
        - "secureHeaders"
        - "compress"
      service: "server-c-canary"
      priority: 200  # Higher priority than the stable route
      tls:
        certResolver: "cloudflare"

    # Default/stable router - used when X-Version is not canary or not present
    server-c:
      rule: "Host(`s1.server.plansync.in`)"
      entryPoints:
        - "web"
        - "websecure"
      middlewares:
        - "secureHeaders"
        - "compress"
      service: "server-c-stable"
      priority: 100
      tls:
        certResolver: "cloudflare"

  services:
    # Canary service
    server-c-canary:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://canary-api:3000"

    # Stable service
    server-c-stable:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://stable-api:3000"

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
